apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCcpQDdGM45buBsZjjD+BD4AnSQGg5iyL80C6e3XTvbXEoxs4Uyo68wzLu8MKyPAG3AXBv7q3MfozYuscQ7pLwBmU/uFpuunqZ8DvYyCLnRvUOa4O9dzGOSDOJyeThAwqp5WOuAfdn99MuRASdT0RMihDUlGyUnjarA21vmsx97qCUWLkZfNuIh1rx+35WQ4EV+W++dd0CBB4qTSPcTMTt8jw/DyAw342chYPUoq/ziZC7knBTfel2yvujng9pzEPPiSr+9GG2lDdZtcOSCHOvn6nw74D6Q6wDVHdSKkW1S+z8XwL3nIC1aieIZAATCWEizW+3ipSHmjtbAIwrsC1BtykXA9TytvtBHXKWdt97Q/XFGzA6mEIbQxtVb2XPUcr/6U+JUik4F1YNe5q0qH0QPyRn9r60u2Oc21w8xftKqS/8YdLnPhaHr2O9dKTGbQ7pqf512MkoyIzGbSNrvGIuQGw0ftUnu9IPllnwYnWCTO5B16bNX1oaQ3UREjzo3kjKvpStty6HcAi5Jsst0zo328fONeMyzcaq/8Q1HE3+ufR9tQKULCEy88z8IjUR320Ym+Fs37jZwg9jmvVi/hjj1ZfBBnMpkxJj46uLZch3mfVnNA4P5FGzvZvU/v33hpP0RJWVDpUQ4GzaE254A+XQoiP3CfCs29xoYmQF6hP97FDUatj+aMxxNw1oi8AVjfTWLdS2dWBD9ikGUIv21uHMN4y0aN7RZjmHzGkYLUTBOdz2hHf0RGgvUN9ZrU2gwx/RExR8il3O1W1R2pewS4RPVLIOX/msCKzptpIOK4lKPvq3zDDzMSeE1Mf5ed+tc4oEJ9888jc4wiov/uNtjcywIqrUPerNn5doPJ61Rs+SDLx3n+Lx9HAXJSu2eHX5z6RSjU1cOPvO+R3sjfaW9K0fWv6Y8l/r7iSzklZdN9W29zntVWndHKHble4Y21y0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

